/*
	Zapytanie do raportu limitów absencji.
*/
  
WITH TYPY_ABSENCJI AS (
    SELECT 'A_UR1' AS KOD, 'urlop wypoczynkowy' AS NAZWA FROM DUAL UNION ALL
    SELECT 'A_UR11', 'urlop na żądanie' FROM DUAL UNION ALL
    SELECT 'UR_NA', 'urlop nauczycieli akademickich' FROM DUAL UNION ALL
    SELECT 'UR31', 'Urlop opieka nad dzieckiem (dniami)' FROM DUAL UNION ALL
    SELECT 'L_CHOR2', 'chorob. opieka nad dzieckiem' FROM DUAL UNION ALL
    SELECT 'L_CHOR3', 'chorob. opieka nad chorym' FROM DUAL UNION ALL
    SELECT 'L_PZO', 'praca zdalna okazjonalna' FROM DUAL
)
SELECT
    OB.OB_PELNY_KOD AS KOD_JEDNOSTKI,
    OB.OB_NAZWA AS NAZW_JEDNOSTKI,
    PRC.PRC_IMIE AS IMIE,
    PRC.PRC_NAZWISKO AS NAZWISKO,
    LA.LA_DG_KOD AS KOD_ABSENCJI,
    TA.NAZWA AS NAZWA_ABSENCJI,
    LA.LA_ROK AS ZA_ROK,
    LD.LD_OD AS OD_DNIA,
    LD.LD_DO AS DO_DNIA,
    LD.LD_POZOSTALO AS DNI_POZOSTALE,
    LD.LD_DNI AS LIMIT_DNI,
    LD.LD_WYKORZYSTANE AS DNI_WYKORZYSTANE,
    LD.LD_WYMIAR AS WYMIAR_DNI,
    GREATEST( LD.LD_DNI - LD.LD_WYMIAR, 0 ) AS ZALEGLE_DNI,
    LD.LD_GODZINY AS LIMIT_GODZIN,
    LD.LD_WYKORZYSTANE_G AS GODZINY_WYKORZYSTANE,
    LD.LD_POZOSTALO_G AS GODZINY_POZOSTALE,
    NVL( LA.LA_PRZENIESIONE, 0 ) AS ZALEGLE_GODZINY
FROM
    EK_PRACOWNICY PRC
    JOIN EK_ZATRUDNIENIE ZAT ON ZAT.ZAT_PRC_ID = PRC.PRC_ID
    JOIN EK_OBIEKTY_W_PRZEDSIEB OB ON ZAT.ZAT_OB_ID = OB.OB_ID
    JOIN EK_LIMITY_ABSENCJI LA ON LA.LA_PRC_ID = ZAT.ZAT_PRC_ID
    JOIN EK_LIMITY_DANE LD ON LA.LA_ID = LD.LD_LA_ID
    JOIN TYPY_ABSENCJI TA ON LA.LA_DG_KOD = TA.KOD
WHERE
    ZAT.ZAT_TYP_UMOWY = 0 -- umowa o pracę
    AND LA.LA_ROK = :P_ROK
    AND ZAT.ZAT_DATA_ZMIANY <= SYSDATE
    AND NVL( ZAT.ZAT_DATA_DO, SYSDATE ) >= SYSDATE
ORDER BY 
    KOD_JEDNOSTKI, 
    NAZWISKO,
    KOD_ABSENCJI
;
