/*
    Zapytanie SQL do wyświetlenia uprawnień użytkowników do magazynów w dziale zaopatrywania.
    Wynik zawiera nazwę użytkownika, imię i nazwisko oraz kolumny z oznaczeniem 'X' dla magazynów, do których mają uprawnienia.
*/

SELECT
    UZT.UZT_NAZWA AS NAZWA_UZYTKOWNIKA,
    UZT.UZT_IMIE || ' ' || UZT.UZT_NAZWISKO1 AS IMIE_NAZWISKO,
    (
        SELECT DISTINCT
            'X'
        FROM
            EAADM.EAT_UZYTKOWNICY UZT1 
            JOIN EGADM1.GMT_UPRAWNIENIA UPR1 ON UPR1.UPR_UZT_NAZWA = UZT1.UZT_NAZWA
            JOIN EGADM1.CSS_OBIEKTY_W_PRZEDSIEB OB1 ON UPR1.UPR_MAG_OB_ID = OB1.OB_ID
            JOIN EGADM1.GMT_MAGAZYNY MAG1 ON MAG1.MAG_OB_ID = OB1.OB_ID
        WHERE
            UZT1.UZT_NAZWA = UZT.UZT_NAZWA
            AND MAG1.MAG_KOD_NR = 'M01'
    ) AS M01,
    (
        SELECT DISTINCT
            'X'
        FROM
            EAADM.EAT_UZYTKOWNICY UZT1 
            JOIN EGADM1.GMT_UPRAWNIENIA UPR1 ON UPR1.UPR_UZT_NAZWA = UZT1.UZT_NAZWA
            JOIN EGADM1.CSS_OBIEKTY_W_PRZEDSIEB OB1 ON UPR1.UPR_MAG_OB_ID = OB1.OB_ID
            JOIN EGADM1.GMT_MAGAZYNY MAG1 ON MAG1.MAG_OB_ID = OB1.OB_ID
        WHERE
            UZT1.UZT_NAZWA = UZT.UZT_NAZWA
            AND MAG1.MAG_KOD_NR = 'M02'
    ) AS M02,
    (
        SELECT DISTINCT
            'X'
        FROM
            EAADM.EAT_UZYTKOWNICY UZT1 
            JOIN EGADM1.GMT_UPRAWNIENIA UPR1 ON UPR1.UPR_UZT_NAZWA = UZT1.UZT_NAZWA
            JOIN EGADM1.CSS_OBIEKTY_W_PRZEDSIEB OB1 ON UPR1.UPR_MAG_OB_ID = OB1.OB_ID
            JOIN EGADM1.GMT_MAGAZYNY MAG1 ON MAG1.MAG_OB_ID = OB1.OB_ID
        WHERE
            UZT1.UZT_NAZWA = UZT.UZT_NAZWA
            AND MAG1.MAG_KOD_NR = 'M03'
    ) AS M03,
    (
        SELECT DISTINCT
            'X'
        FROM
            EAADM.EAT_UZYTKOWNICY UZT1 
            JOIN EGADM1.GMT_UPRAWNIENIA UPR1 ON UPR1.UPR_UZT_NAZWA = UZT1.UZT_NAZWA
            JOIN EGADM1.CSS_OBIEKTY_W_PRZEDSIEB OB1 ON UPR1.UPR_MAG_OB_ID = OB1.OB_ID
            JOIN EGADM1.GMT_MAGAZYNY MAG1 ON MAG1.MAG_OB_ID = OB1.OB_ID
        WHERE
            UZT1.UZT_NAZWA = UZT.UZT_NAZWA
            AND MAG1.MAG_KOD_NR = 'M04'
    ) AS M04,
    (
        SELECT DISTINCT
            'X'
        FROM
            EAADM.EAT_UZYTKOWNICY UZT1 
            JOIN EGADM1.GMT_UPRAWNIENIA UPR1 ON UPR1.UPR_UZT_NAZWA = UZT1.UZT_NAZWA
            JOIN EGADM1.CSS_OBIEKTY_W_PRZEDSIEB OB1 ON UPR1.UPR_MAG_OB_ID = OB1.OB_ID
            JOIN EGADM1.GMT_MAGAZYNY MAG1 ON MAG1.MAG_OB_ID = OB1.OB_ID
        WHERE
            UZT1.UZT_NAZWA = UZT.UZT_NAZWA
            AND MAG1.MAG_KOD_NR = 'M05'
    ) AS M05,
    (
        SELECT DISTINCT
            'X'
        FROM
            EAADM.EAT_UZYTKOWNICY UZT1 
            JOIN EGADM1.GMT_UPRAWNIENIA UPR1 ON UPR1.UPR_UZT_NAZWA = UZT1.UZT_NAZWA
            JOIN EGADM1.CSS_OBIEKTY_W_PRZEDSIEB OB1 ON UPR1.UPR_MAG_OB_ID = OB1.OB_ID
            JOIN EGADM1.GMT_MAGAZYNY MAG1 ON MAG1.MAG_OB_ID = OB1.OB_ID
        WHERE
            UZT1.UZT_NAZWA = UZT.UZT_NAZWA
            AND MAG1.MAG_KOD_NR = 'M06'
    ) AS M06,
    (
        SELECT DISTINCT
            'X'
        FROM
            EAADM.EAT_UZYTKOWNICY UZT1 
            JOIN EGADM1.GMT_UPRAWNIENIA UPR1 ON UPR1.UPR_UZT_NAZWA = UZT1.UZT_NAZWA
            JOIN EGADM1.CSS_OBIEKTY_W_PRZEDSIEB OB1 ON UPR1.UPR_MAG_OB_ID = OB1.OB_ID
            JOIN EGADM1.GMT_MAGAZYNY MAG1 ON MAG1.MAG_OB_ID = OB1.OB_ID
        WHERE
            UZT1.UZT_NAZWA = UZT.UZT_NAZWA
            AND MAG1.MAG_KOD_NR = 'M07'
    ) AS M07,
    (
        SELECT DISTINCT
            'X'
        FROM
            EAADM.EAT_UZYTKOWNICY UZT1 
            JOIN EGADM1.GMT_UPRAWNIENIA UPR1 ON UPR1.UPR_UZT_NAZWA = UZT1.UZT_NAZWA
            JOIN EGADM1.CSS_OBIEKTY_W_PRZEDSIEB OB1 ON UPR1.UPR_MAG_OB_ID = OB1.OB_ID
            JOIN EGADM1.GMT_MAGAZYNY MAG1 ON MAG1.MAG_OB_ID = OB1.OB_ID
        WHERE
            UZT1.UZT_NAZWA = UZT.UZT_NAZWA
            AND MAG1.MAG_KOD_NR = 'M08'
    ) AS M08,
    (
        SELECT DISTINCT
            'X'
        FROM
            EAADM.EAT_UZYTKOWNICY UZT1 
            JOIN EGADM1.GMT_UPRAWNIENIA UPR1 ON UPR1.UPR_UZT_NAZWA = UZT1.UZT_NAZWA
            JOIN EGADM1.CSS_OBIEKTY_W_PRZEDSIEB OB1 ON UPR1.UPR_MAG_OB_ID = OB1.OB_ID
            JOIN EGADM1.GMT_MAGAZYNY MAG1 ON MAG1.MAG_OB_ID = OB1.OB_ID
        WHERE
            UZT1.UZT_NAZWA = UZT.UZT_NAZWA
            AND MAG1.MAG_KOD_NR = 'M09'
    ) AS M09
FROM
    EAADM.EAT_UZYTKOWNICY UZT
WHERE
    UPPER( UZT.UZT_BIURO ) = 'DZIAŁ ZAOPATRYWANIA'
    AND UZT.UZT_F_USUNIETY = 'N'
ORDER BY
     UZT.UZT_NAZWISKO1, UZT.UZT_IMIE
;
