/*
    Zapytanie SQL do wyświetlenia uprawnień użytkowników do magazynów w dziale zaopatrywania.
    Wynik zawiera nazwę użytkownika, imię i nazwisko oraz kolumny z oznaczeniem 'X' dla magazynów, do których mają uprawnienia.
*/

SELECT
    UZT.UZT_NAZWA AS NAZWA_UZYTKOWNIKA,
    UZT.UZT_IMIE || ' ' || UZT.UZT_NAZWISKO1 AS IMIE_NAZWISKO,
    MAX( CASE WHEN MAG.MAG_KOD_NR = 'M01' THEN 'X' ELSE '0' END ) AS M01,
    MAX( CASE WHEN MAG.MAG_KOD_NR = 'M02' THEN 'X' ELSE '0' END ) AS M02,
    MAX( CASE WHEN MAG.MAG_KOD_NR = 'M03' THEN 'X' ELSE '0' END ) AS M03,
    MAX( CASE WHEN MAG.MAG_KOD_NR = 'M04' THEN 'X' ELSE '0' END ) AS M04,
    MAX( CASE WHEN MAG.MAG_KOD_NR = 'M05' THEN 'X' ELSE '0' END ) AS M05,
    MAX( CASE WHEN MAG.MAG_KOD_NR = 'M06' THEN 'X' ELSE '0' END ) AS M06,
    MAX( CASE WHEN MAG.MAG_KOD_NR = 'M07' THEN 'X' ELSE '0' END ) AS M07,
    MAX( CASE WHEN MAG.MAG_KOD_NR = 'M08' THEN 'X' ELSE '0' END ) AS M08,
    MAX( CASE WHEN MAG.MAG_KOD_NR = 'M09' THEN 'X' ELSE '0' END ) AS M09
FROM
    EAADM.EAT_UZYTKOWNICY UZT
    LEFT JOIN EGADM1.GMT_UPRAWNIENIA UPR ON UPR.UPR_UZT_NAZWA = UZT.UZT_NAZWA
    LEFT JOIN EGADM1.CSS_OBIEKTY_W_PRZEDSIEB OB ON UPR.UPR_MAG_OB_ID = OB.OB_ID
    LEFT JOIN EGADM1.GMT_MAGAZYNY MAG ON MAG.MAG_OB_ID = OB.OB_ID
WHERE
    UPPER( UZT.UZT_BIURO ) = 'DZIAŁ ZAOPATRYWANIA'
    AND UZT.UZT_F_USUNIETY = 'N'
GROUP BY
    UZT.UZT_NAZWA,
    UZT.UZT_IMIE,
    UZT.UZT_NAZWISKO1
ORDER BY
    UZT.UZT_NAZWISKO1, UZT.UZT_IMIE
;
